cosmos/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.decorators import login_required
from btp import views as btp_views
from accounts import urls as accounts_urls
from posts import views as posts_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve as static_serve
import settings
urlpatterns = [
	url(r'^$', login_required(btp_views.IndexView.as_view()), name='homepage'),
	url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^btp/', include('btp.urls', namespace='btp')),
    
    url(r'^issues-and-suggestions/', include('gp.urls')),

    url(r'^polls/', include('polls.urls')),
    url(r'^roombookings/', include('polls.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

	url(r'^feasta/', include('feasta.urls')),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^posts/', include("posts.urls", namespace='posts')),
    url(r'courses/', include("courses.urls", namespace="courses"))


]
handler404 = 'btp.views.page_not_found'

# During Development Phase
if settings.DEBUG ==True:
	 urlpatterns += staticfiles_urlpatterns()

	 print staticfiles_urlpatterns()

if settings.SERVE_MEDIA:
    urlpatterns += (
        url(r'media/(?P<path>.*)$', static_serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True }),
        url(r'static/(?P<path>.*)$', static_serve,
            {'document_root': settings.STATIC_ROOT, }),
)

gp/urls.py
from django.conf.urls import url
from gp.views import *
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import password_change

urlpatterns = [
			url(r'^$', HomeView.as_view()),
			url(r'^complaint/post/$',PostComplaint.as_view(),name = 'postcomplaint'),
			url(r'^complaints/view/$',ViewComplaintByDomain.as_view(),name= 'complaints'),
			url(r'^upvote/complaint/',Upvotes,name = 'upvote'),
			url(r'^mycomplaints/$',viewMyComplaints.as_view(),name='mycomplaints'),
			url(r'^submit/suggestion/$', submitSuggestion, name='submitsuggestion'),
			url(r'^get/suggestion/$', getSuggestions, name='getsuggestion'),
			]

posts/urls.py
from django.conf.urls import url
from django.contrib import admin
app_name = 'posts'

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	exam_schedule,
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create,name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete,name = 'delete'),
	url(r'^exam_schedule',exam_schedule),#for showing exam_schedule

    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify


from markdown_deux import markdown
from comments.models import Comment

from .utils import get_read_time
# Create your models here.
# MVC MODEL VIEW CONTROLLER


#Post.objects.all()
#Post.objects.create(user=user, title="Some time")

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" %(new_id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True, 
            width_field="width_field", 
            height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=True)
    read_time =  models.IntegerField(default=0) # models.TimeField(null=True, blank=True) #assume minutes
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
        ]

posts/views.py
try:
    from urllib import quote_plus #python 2
except:
    pass

try:
    from urllib.parse import quote_plus #python 3
except:
    pass

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404,HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post
from django.contrib.auth.models import User, Group



def post_create(request):
	#nees to change this
	if not request.user.is_authenticated  and not request.user.is_superuser:
		raise Http404


	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		# message success
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)

def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	if instance.publish > timezone.now().date() or instance.draft:
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	share_string = quote_plus(instance.content)

	initial_data = {
			"content_type": instance.get_content_type,
			"object_id": instance.id
	}
	form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid() and request.user.is_authenticated():
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get('object_id')
		content_data = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()


		new_comment, created = Comment.objects.get_or_create(
							user = request.user,
							content_type= content_type,
							object_id = obj_id,
							content = content_data,
							parent = parent_obj,
						)
		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

	comments = instance.comments
	context = {
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
		"comments": comments,
		"comment_form":form,
	}
	return render(request, "post_detail.html", context)

def post_list(request):
	today = timezone.now().date()
	queryset_list = Post.objects.active() #.order_by("-timestamp")
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()

	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(queryset_list, 8) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"object_list": queryset,
		"title": "List",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request, "post_list.html", context)





def post_update(request, slug=None):
	if not request.user.is_authenticated  and not request.user.is_superuser:
		raise Http404

	instance = get_object_or_404(Post, slug=slug)
	if instance.user != request.user and not request.user.is_superuser :
		return HttpResponseForbidden()
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "post_form.html", context)



def post_delete(request, slug=None):
	if not request.user.is_authenticated  and not request.user.is_superuser :
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	if instance.user != request.user and not request.user.is_superuser:
		return HttpResponseForbidden()
	instance.delete()
	messages.success(request, "Successfully deleted")
	return redirect("posts:list")


###
#for showing the exam schedule

def exam_schedule(request):
    with open('/var/www/cosmosenv/cosmos/exam_schedule.pdf', 'r') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=exam_schedule.pdf'
        return response
    pdf.closed

templates/base.html
{% load staticfiles %}
{% load humanize %}
<!doctype html>
<html lang="en">
<head>
	{% block title %}<title>{{ title }}</title>{% endblock %}
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A project of NSA, IIITS - developed by Sahal Sajjad">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" href="{% static 'btp/img/iiits-logo.png' %}">
	

	<link rel="stylesheet" type="text/css" href="{% static 'btp/css/font-awesome.min.css' %}">
  {% block bootstrap_css %}
	<link rel="stylesheet" href="{% static 'index/css/bootstrap.min.css' %}">
  {% endblock %}
  <link rel="stylesheet" href="{% static 'index/css/material.min.css' %}">
    <link rel="stylesheet" href="{% static 'btp/css/styles.css' %}">
	<script src="{% static 'btp/js/jquery.min.js' %}"></script>
	<script src="{% static 'btp/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'btp/js/script.js' %}"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
{% block nav %}
  {% include 'base/nav.html' %}
{% endblock %}
<div class="container-fluid" style="min-height:90vh;">
  {% block sidenav %}
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
      {% include 'btp/sidenav.html' %}
    </div>
  {% endblock %}
  
  {% block main %}
    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9" style="padding-top:25px;">
      {% block maincontent %}
      {% include 'btp/main.html' %}
      {% endblock %}
    </div>    
  {% endblock %}

</div> 
{% block footer %}
    <footer><center style="font-size: 12px;" class="card-subtitle">Developed by <abbr title="Network, Server Administrator, Webmaster, IIITS">Sahal Sajjad</abbr></center></footer>
  {% endblock %}  
</body>
</html>

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
</div>
{% endblock content %}

templates/invalid.html
{% block content %}
	<h2> Login Failed </h2>
	<p>Click <a href="/polls/accounts/login/">here</a> to login again. </p>
{% endblock %}

templates/login.html
{% block content %}
	<!DOCTYPE html>
	<html >
	<head>
	  <meta charset="UTF-8">
	  <title>Material Design Login Form</title>
	  <style type="text/css">
	  	* { box-sizing:border-box; }

	  	body {
	  		font-family: Helvetica;
	  		background: #eee;
	  	  -webkit-font-smoothing: antialiased;
	  	}

	  	hgroup { 
	  		text-align:center;
	  		margin-top: 4em;
	  	}

	  	h1, h3 { font-weight: 300; }

	  	h1 { color: #636363; }

	  	h3 { color: #4a89dc; }

	  	form {
	  		width: 380px;
	  		margin: 4em auto;
	  		padding: 3em 2em 2em 2em;
	  		background: #fafafa;
	  		border: 1px solid #ebebeb;
	  		box-shadow: rgba(0,0,0,0.14902) 0px 1px 1px 0px,rgba(0,0,0,0.09804) 0px 1px 2px 0px;
	  	}

	  	.group { 
	  		position: relative; 
	  		margin-bottom: 45px; 
	  	}

	  	input {
	  		font-size: 18px;
	  		padding: 10px 10px 10px 5px;
	  		-webkit-appearance: none;
	  		display: block;
	  		background: #fafafa;
	  		color: #636363;
	  		width: 100%;
	  		border: none;
	  		border-radius: 0;
	  		border-bottom: 1px solid #757575;
	  	}

	  	input:focus { outline: none; }


	  	/* Label */

	  	label {
	  		color: #999; 
	  		font-size: 18px;
	  		font-weight: normal;
	  		position: absolute;
	  		pointer-events: none;
	  		left: 5px;
	  		top: 10px;
	  		-webkit-transition:all 0.2s ease;
	  		transition: all 0.2s ease;
	  	}


	  	/* active */

	  	input:focus ~ label, input.used ~ label {
	  		top: -20px;
	  	  -webkit-transform: scale(.75);
	  	          transform: scale(.75); left: -2px;
	  		/* font-size: 14px; */
	  		color: #4a89dc;
	  	}


	  	/* Underline */

	  	.bar {
	  		position: relative;
	  		display: block;
	  		width: 100%;
	  	}

	  	.bar:before, .bar:after {
	  		content: '';
	  		height: 2px; 
	  		width: 0;
	  		bottom: 1px; 
	  		position: absolute;
	  		background: #4a89dc; 
	  		-webkit-transition:all 0.2s ease; 
	  		transition: all 0.2s ease;
	  	}

	  	.bar:before { left: 50%; }

	  	.bar:after { right: 50%; }


	  	/* active */

	  	input:focus ~ .bar:before, input:focus ~ .bar:after { width: 50%; }


	  	/* Highlight */

	  	.highlight {
	  		position: absolute;
	  		height: 60%; 
	  		width: 100px; 
	  		top: 25%; 
	  		left: 0;
	  		pointer-events: none;
	  		opacity: 0.5;
	  	}


	  	/* active */

	  	input:focus ~ .highlight {
	  		-webkit-animation: inputHighlighter 0.3s ease;
	  		        animation: inputHighlighter 0.3s ease;
	  	}


	  	/* Animations */

	  	@-webkit-keyframes inputHighlighter {
	  		from { background: #4a89dc; }
	  		to 	{ width: 0; background: transparent; }
	  	}

	  	@keyframes inputHighlighter {
	  		from { background: #4a89dc; }
	  		to 	{ width: 0; background: transparent; }
	  	}


	  	/* Button */

	  	.button {
	  	  position: relative;
	  	  display: inline-block;
	  	  padding: 12px 24px;
	  	  margin: .3em 0 1em 0;
	  	  width: 100%;
	  	  vertical-align: middle;
	  	  color: #fff;
	  	  font-size: 16px;
	  	  line-height: 20px;
	  	  -webkit-font-smoothing: antialiased;
	  	  text-align: center;
	  	  letter-spacing: 1px;
	  	  background: transparent;
	  	  border: 0;
	  	  border-bottom: 2px solid #3160B6;
	  	  cursor: pointer;
	  	  -webkit-transition:all 0.15s ease;
	  	  transition: all 0.15s ease;
	  	}
	  	.button:focus { outline: 0; }


	  	/* Button modifiers */

	  	.buttonBlue {
	  	  background: #4a89dc;
	  	  text-shadow: 1px 1px 0 rgba(39, 110, 204, .5);
	  	}

	  	.buttonBlue:hover { background: #357bd8; }


	  	/* Ripples container */

	  	.ripples {
	  	  position: absolute;
	  	  top: 0;
	  	  left: 0;
	  	  width: 100%;
	  	  height: 100%;
	  	  overflow: hidden;
	  	  background: transparent;
	  	}


	  	/* Ripples circle */

	  	.ripplesCircle {
	  	  position: absolute;
	  	  top: 50%;
	  	  left: 50%;
	  	  -webkit-transform: translate(-50%, -50%);
	  	          transform: translate(-50%, -50%);
	  	  opacity: 0;
	  	  width: 0;
	  	  height: 0;
	  	  border-radius: 50%;
	  	  background: rgba(255, 255, 255, 0.25);
	  	}

	  	.ripples.is-active .ripplesCircle {
	  	  -webkit-animation: ripples .4s ease-in;
	  	          animation: ripples .4s ease-in;
	  	}


	  	/* Ripples animation */

	  	@-webkit-keyframes ripples {
	  	  0% { opacity: 0; }

	  	  25% { opacity: 1; }

	  	  100% {
	  	    width: 200%;
	  	    padding-bottom: 200%;
	  	    opacity: 0;
	  	  }
	  	}

	  	@keyframes ripples {
	  	  0% { opacity: 0; }

	  	  25% { opacity: 1; }

	  	  100% {
	  	    width: 200%;
	  	    padding-bottom: 200%;
	  	    opacity: 0;
	  	  }
	  	}

	  	footer { text-align: center; }

	  	footer p {
	  		color: #888;
	  		font-size: 13px;
	  		letter-spacing: .4px;
	  	}

	  	footer a {
	  		color: #4a89dc;
	  		text-decoration: none;
	  		-webkit-transition:all .2s ease;
	  		transition: all .2s ease;
	  	}

	  	footer a:hover {
	  		color: #666;
	  		text-decoration: underline;
	  	}

	  	footer img {
	  		width: 80px;
	  		-webkit-transition:all .2s ease;
	  		transition: all .2s ease;
	  	}

	  	footer img:hover { opacity: .83; }

	  	footer img:focus , footer a:focus { outline: none; }
	  </style>
	  
	</head>

	<body>		
	{% if form.errors %}
		<p class="error"> Sorry, that's not a valid username or password </p>
	{% endif %}
	<form action = "/polls/accounts/auth/" method="post">{% csrf_token %}
	  <div class="group">
	    <input type="text" name="username" value="" id="username"><span class="highlight"></span><span class="bar"></span>
	    <label for="username">Username</label>
	  </div>
	  <div class="group">
	    <input type="password" name="password" value="" id="password"><span class="highlight"></span><span class="bar"></span>
	    <label for="password">Password</label>
	  </div>
	  <button type="submit" class="button buttonBlue" value="login">Login
	    <div class="ripples buttonRipples"><span class="ripplesCircle"></span></div>
	  </button>
	</form>
	  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

	    <script>
	    	$(window, document, undefined).ready(function() {

	    	  $('input').blur(function() {
	    	    var $this = $(this);
	    	    if ($this.val())
	    	      $this.addClass('used');
	    	    else
	    	      $this.removeClass('used');
	    	  });

	    	  var $ripples = $('.ripples');

	    	  $ripples.on('click.Ripples', function(e) {

	    	    var $this = $(this);
	    	    var $offset = $this.parent().offset();
	    	    var $circle = $this.find('.ripplesCircle');

	    	    var x = e.pageX - $offset.left;
	    	    var y = e.pageY - $offset.top;

	    	    $circle.css({
	    	      top: y + 'px',
	    	      left: x + 'px'
	    	    });

	    	    $this.addClass('is-active');

	    	  });

	    	  $ripples.on('animationend webkitAnimationEnd mozAnimationEnd oanimationend MSAnimationEnd', function(e) {
	    	  	$(this).removeClass('is-active');
	    	  });

	    	});
	    </script>

	</body>
	</html>
	<!-- <form action = "/polls/accounts/auth/" method="post">{% csrf_token %}
		<label for="username">Username:</label>
		<input type="text" name="username" value="" id = "username">
		<label for="password">Password:</label>
		<input type="password" name="password" value="" id="password">
		<input type="submit" value="login"/>
	</form> -->
{% endblock %}

templates/main.html
{% load staticfiles %}

<html>
<head>
<title>{% block head_title %}Student Projects{% endblock head_title %}</title>

<link rel='stylesheet' href='{% static "posts/css/bootstrap.min.css" %}' />
 <link href='{% static "posts/css/simple-sidebar.css" %}' rel="stylesheet">
<link rel='stylesheet' href='{% static "posts/css/base.css" %}' />
<style>
{% block style %}{% endblock style %}
</style>

{% block head_extra %} {% endblock head_extra %}
</head>
<body>
 
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand" >
                    <a href='{% url "posts:list" %}'>
                       Student Projects
                    </a>
                </li>
                
                {% block side_bar_list %}
                {% endblock %}
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <a href="#menu-toggle" class="btn btn-info btn-lg" id="menu-toggle"> 
                        <span class="glyphicon glyphicon-transfer"></span> Menu
                        </a>

                        {% block base_body %}

                        {% endblock %}

                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

    <script src='{% static "js/jquery.js" %}'></script>

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "js/bootstrap.min.js" %}'></script>

    <script src='{% static "js/marked.min.js" %}'></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>



<script type="text/javascript">
$(document).ready(function(){
    $(".content-markdown").each(function(){
            var content = $(this).text()
            var markedContent = marked(content)
            $(this).html(markedContent)
    })
    $(".post-detail-item img").each(function(){
            $(this).addClass("img-responsive");
    })

    

    var contentInput = $("#id_content");

    function setContent(value){
        var markedContent = marked(value)
        $("#preview-content").html(markedContent)
        $("#preview-content img").each(function(){
            $(this).addClass("img-responsive")
        })
    }
    setContent(contentInput.val())

    contentInput.keyup(function(){
        var newContent = $(this).val()
        setContent(newContent)
    })

    var titleInput = $("#id_title");
    


    function setTitle(value) {
        $("#preview-title").text(value)
    }
    setTitle(titleInput.val())

    titleInput.keyup(function(){
        var newContent = $(this).val()
        setTitle(newContent)
    })

    $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().next(".comment-reply").fadeToggle();
    })


    // preview-title
    // preview-content

})

</script>
    
   

</body>

</html>

templates/messages_display.html
 {% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

templates/post_form.html
{% extends "posts_base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %} 
{{ form.media }}

{% endblock head_extra %}



{% block content %}

<div class='col-sm-6'>
<h1>Form</h1>


<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Create Post' />
</form>
</div>
{% endblock content %}

templates/posts_base.html
{% extends "main.html" %}
{% load groupCheck %}


{% block side_bar_list%}

        {% if not request.user.is_authenticated %}
        <li ><a href='{% url "login" %}'>Login</a></li>
         <li ><a href='{% url "register" %}'>Register</a></li>
        {% else %}
        <li ><a href='{% url "posts:create" %}'>Create</a></li>
        <li ><a href='{% url "logout" %}'>Logout</a></li>
        {% endif %}
        {% block sidebar %}{% endblock sidebar %}

{%endblock%}

{% block base_body %}
{% include "messages_display.html" %}
<div class='container-fluid'> 
    
{% block content %}{% endblock content %}
</div>
{% endblock %}

</html>